/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/839nAks2GYP
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Table, TableHeader, TableRow, TableHead, TableBody, TableCell } from "../ui/table"
import { Badge } from "../ui/badge"

export function PokemonTableV0() {
  return (
    <div className="border rounded-lg overflow-hidden">
      <Table>
        <TableHeader>
          <TableRow>
            <TableHead>Name</TableHead>
            <TableHead>Image</TableHead>
            <TableHead>Types</TableHead>
          </TableRow>
        </TableHeader>
        <TableBody>
          <TableRow>
            <TableCell className="font-bold">Pikachu</TableCell>
            <TableCell>
              <img
                src="/placeholder.svg"
                alt="Pikachu"
                width={48}
                height={48}
                className="aspect-square object-cover rounded-md"
              />
            </TableCell>
            <TableCell>
              <Badge variant="outline" className="bg-[#f1c40f] text-[#f1c40f]-foreground">
                Electric
              </Badge>
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell className="font-bold">Charizard</TableCell>
            <TableCell>
              <img
                src="/placeholder.svg"
                alt="Charizard"
                width={48}
                height={48}
                className="aspect-square object-cover rounded-md"
              />
            </TableCell>
            <TableCell>
              <Badge variant="outline" className="bg-[#e67e22] text-[#e67e22]-foreground">
                Fire
              </Badge>
              <Badge variant="outline" className="bg-[#7f8c8d] text-[#7f8c8d]-foreground">
                Flying
              </Badge>
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell className="font-bold">Squirtle</TableCell>
            <TableCell>
              <img
                src="/placeholder.svg"
                alt="Squirtle"
                width={48}
                height={48}
                className="aspect-square object-cover rounded-md"
              />
            </TableCell>
            <TableCell>
              <Badge variant="outline" className="bg-[#3498db] text-[#3498db]-foreground">
                Water
              </Badge>
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell className="font-bold">Bulbasaur</TableCell>
            <TableCell>
              <img
                src="/placeholder.svg"
                alt="Bulbasaur"
                width={48}
                height={48}
                className="aspect-square object-cover rounded-md"
              />
            </TableCell>
            <TableCell>
              <Badge variant="outline" className="bg-[#2ecc71] text-[#2ecc71]-foreground">
                Grass
              </Badge>
              <Badge variant="outline" className="bg-[#9b59b6] text-[#9b59b6]-foreground">
                Poison
              </Badge>
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell className="font-bold">Eevee</TableCell>
            <TableCell>
              <img
                src="/placeholder.svg"
                alt="Eevee"
                width={48}
                height={48}
                className="aspect-square object-cover rounded-md"
              />
            </TableCell>
            <TableCell>
              <Badge variant="outline" className="bg-[#f1c40f] text-[#f1c40f]-foreground">
                Normal
              </Badge>
            </TableCell>
          </TableRow>
        </TableBody>
      </Table>
    </div>
  )
}
