/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/2LyAaSq3oRh
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Archivo } from 'next/font/google'
import { DM_Sans } from 'next/font/google'

archivo({
  subsets: ['latin'],
  display: 'swap',
})

dm_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Input } from "components/ui/input"
import { type JSX, type SVGProps } from "react"

export function Pokedex() {
  return (
    <div className="flex flex-col min-h-screen bg-[#f0f0f0]">
      <header className="bg-[#e3350d] py-4 px-6 shadow-md">
        <div className="container mx-auto flex items-center justify-between">
          <Link href="#" className="text-white font-bold text-2xl" prefetch={false}>
            Pokédex
          </Link>
          <div className="relative">
            <Input
              type="text"
              placeholder="Search Pokémon..."
              className="bg-white rounded-full py-2 px-4 pr-10 text-sm focus:outline-none focus:ring-2 focus:ring-[#e3350d] focus:border-transparent"
            />
            <SearchIcon className="absolute right-3 top-1/2 transform -translate-y-1/2 text-gray-400 h-5 w-5" />
          </div>
        </div>
      </header>
      <main className="container mx-auto py-8">
        <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
          <div className="bg-white rounded-lg shadow-md overflow-hidden">
            <div className="relative">
              <img
                src="/placeholder.svg"
                alt="Pokémon"
                width={300}
                height={300}
                className="w-full h-48 object-cover"
                style={{ aspectRatio: "300/300", objectFit: "cover" }}
              />
              <div className="absolute top-2 left-2 bg-[#e3350d] text-white font-bold px-3 py-1 rounded-full text-xs">
                #001
              </div>
            </div>
            <div className="p-4">
              <h3 className="text-lg font-bold text-gray-800 mb-2">Bulbasaur</h3>
              <div className="flex justify-between items-center">
                <div className="flex items-center space-x-2">
                  <GrapeIcon className="h-5 w-5 text-green-500" />
                  <BugIcon className="h-5 w-5 text-purple-500" />
                </div>
                <Link
                  href="#"
                  className="bg-[#e3350d] text-white font-bold py-2 px-4 rounded-full text-sm hover:bg-[#c02b0a] transition-colors"
                  prefetch={false}
                >
                  View Details
                </Link>
              </div>
            </div>
          </div>
          <div className="bg-white rounded-lg shadow-md overflow-hidden">
            <div className="relative">
              <img
                src="/placeholder.svg"
                alt="Pokémon"
                width={300}
                height={300}
                className="w-full h-48 object-cover"
                style={{ aspectRatio: "300/300", objectFit: "cover" }}
              />
              <div className="absolute top-2 left-2 bg-[#e3350d] text-white font-bold px-3 py-1 rounded-full text-xs">
                #004
              </div>
            </div>
            <div className="p-4">
              <h3 className="text-lg font-bold text-gray-800 mb-2">Charmander</h3>
              <div className="flex justify-between items-center">
                <div className="flex items-center space-x-2">
                  <FlameIcon className="h-5 w-5 text-red-500" />
                </div>
                <Link
                  href="#"
                  className="bg-[#e3350d] text-white font-bold py-2 px-4 rounded-full text-sm hover:bg-[#c02b0a] transition-colors"
                  prefetch={false}
                >
                  View Details
                </Link>
              </div>
            </div>
          </div>
          <div className="bg-white rounded-lg shadow-md overflow-hidden">
            <div className="relative">
              <img
                src="/placeholder.svg"
                alt="Pokémon"
                width={300}
                height={300}
                className="w-full h-48 object-cover"
                style={{ aspectRatio: "300/300", objectFit: "cover" }}
              />
              <div className="absolute top-2 left-2 bg-[#e3350d] text-white font-bold px-3 py-1 rounded-full text-xs">
                #007
              </div>
            </div>
            <div className="p-4">
              <h3 className="text-lg font-bold text-gray-800 mb-2">Squirtle</h3>
              <div className="flex justify-between items-center">
                <div className="flex items-center space-x-2">
                  <GlassWaterIcon className="h-5 w-5 text-blue-500" />
                </div>
                <Link
                  href="#"
                  className="bg-[#e3350d] text-white font-bold py-2 px-4 rounded-full text-sm hover:bg-[#c02b0a] transition-colors"
                  prefetch={false}
                >
                  View Details
                </Link>
              </div>
            </div>
          </div>
          <div className="bg-white rounded-lg shadow-md overflow-hidden">
            <div className="relative">
              <img
                src="/placeholder.svg"
                alt="Pokémon"
                width={300}
                height={300}
                className="w-full h-48 object-cover"
                style={{ aspectRatio: "300/300", objectFit: "cover" }}
              />
              <div className="absolute top-2 left-2 bg-[#e3350d] text-white font-bold px-3 py-1 rounded-full text-xs">
                #025
              </div>
            </div>
            <div className="p-4">
              <h3 className="text-lg font-bold text-gray-800 mb-2">Pikachu</h3>
              <div className="flex justify-between items-center">
                <div className="flex items-center space-x-2">
                  <BellElectricIcon className="h-5 w-5 text-yellow-500" />
                </div>
                <Link
                  href="#"
                  className="bg-[#e3350d] text-white font-bold py-2 px-4 rounded-full text-sm hover:bg-[#c02b0a] transition-colors"
                  prefetch={false}
                >
                  View Details
                </Link>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  )
}

function BellElectricIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18.8 4A6.3 8.7 0 0 1 20 9" />
      <path d="M9 9h.01" />
      <circle cx="9" cy="9" r="7" />
      <rect width="10" height="6" x="4" y="16" rx="2" />
      <path d="M14 19c3 0 4.6-1.6 4.6-1.6" />
      <circle cx="20" cy="16" r="2" />
    </svg>
  )
}


function BugIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 2 1.88 1.88" />
      <path d="M14.12 3.88 16 2" />
      <path d="M9 7.13v-1a3.003 3.003 0 1 1 6 0v1" />
      <path d="M12 20c-3.3 0-6-2.7-6-6v-3a4 4 0 0 1 4-4h4a4 4 0 0 1 4 4v3c0 3.3-2.7 6-6 6" />
      <path d="M12 20v-9" />
      <path d="M6.53 9C4.6 8.8 3 7.1 3 5" />
      <path d="M6 13H2" />
      <path d="M3 21c0-2.1 1.7-3.9 3.8-4" />
      <path d="M20.97 5c0 2.1-1.6 3.8-3.5 4" />
      <path d="M22 13h-4" />
      <path d="M17.2 17c2.1.1 3.8 1.9 3.8 4" />
    </svg>
  )
}


function FlameIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M8.5 14.5A2.5 2.5 0 0 0 11 12c0-1.38-.5-2-1-3-1.072-2.143-.224-4.054 2-6 .5 2.5 2 4.9 4 6.5 2 1.6 3 3.5 3 5.5a7 7 0 1 1-14 0c0-1.153.433-2.294 1-3a2.5 2.5 0 0 0 2.5 2.5z" />
    </svg>
  )
}


function GlassWaterIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M15.2 22H8.8a2 2 0 0 1-2-1.79L5 3h14l-1.81 17.21A2 2 0 0 1 15.2 22Z" />
      <path d="M6 12a5 5 0 0 1 6 0 5 5 0 0 0 6 0" />
    </svg>
  )
}


function GrapeIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 5V2l-5.89 5.89" />
      <circle cx="16.6" cy="15.89" r="3" />
      <circle cx="8.11" cy="7.4" r="3" />
      <circle cx="12.35" cy="11.65" r="3" />
      <circle cx="13.91" cy="5.85" r="3" />
      <circle cx="18.15" cy="10.09" r="3" />
      <circle cx="6.56" cy="13.2" r="3" />
      <circle cx="10.8" cy="17.44" r="3" />
      <circle cx="5" cy="19" r="3" />
    </svg>
  )
}


function SearchIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}
